### ISSUE TITLE
scopes/namespace ALL packages

### ISSUE THREAD

**Issue by Jakobud** [EverythingStays/EverythingStays#5]
The #1 biggest problem with NPM is that they built it without requiring namespaces (scopes is what they call it) for packages. Having namespaces would have solved the majority of the recent issues.

What I'm talking about is that every single package install should require a namespace. The namespace is the "owner" or account name of the person/organization who created and published the package.

The whole of NPM's problem this past 2 weeks started because some random person made a package called "kik". You install(ed) it via npm using:

```
npm install kik
```

The problem is that npm modules have **unique names**. This person who made this package OWNED the package name kik, which is what lead to the naming controversy, package name ownership change, and angry user un-publishing a popular package.

NPM does have scopes (their version of namespaces) but they don't require them. Huge mistake in my opinion. Because they don't require namespaces, then the package name `kik` really is owned by a single person/organization.

If npm actually required scopes, then you would be FORCED (which is a good thing) to use a scope when installing a package:

```
npm install @johndoe/kik
```

or

```
npm install @kikcompany/kik
```

If you try to install a package without a namespace, you get an error. That's how it should work. This would solve all naming conflicts. There could be a million different packages called `kik` and it wouldn't be a problem.

Unfortunately, even though `npm` has the ability to use scopes, it would be EXTREMELY difficult to go back and start requiring scopes. Probably 99.999% of `package.json` files don't have scopes specified so there would be a tremendous amount of broken apps if they all the sudden started requiring scopes. The source of the problem is that npm did not require scopes FROM THE BEGINNING.

If you want to see a package manager that successfully uses (and requires) scopes, see PHP's Composer.

So my advice if you are going to start an npm competitor, I would HIGHLY recommend requiring scopes/namespaces for all packages. Otherwise you set yourself up for issues and, as you can see with npm, it's not something you can easily change later.

**Comment by victorb** [comment]
> So my advice if you are going to start an npm competitor, I would HIGHLY recommend requiring scopes/namespaces for all packages.

Something that might not be clear from the homepage, this is NOT a NPM competitor. I love NPM and most stuff they are doing. This is simply a different way of distributing the modules themselves, while leveraging the NPM cli.

As with EverythingStays, there is no concept of "owning" a module or a name. You use a name you find suitable and you use that. Others might use the same name, but as long as you're publishing your hash in your trusted way, others won't have any problems getting the right thing.

The name is not important, except for `require('lodash')` inside the code (to let the code be clear)

Does that make sense for you?

**Comment by Jakobud** [comment]
Ah yes I misread the original intentions of the readme. Got it now :-) So you are talking about sort of like BitTorrent for package distribution?

**Comment by victorb** [comment]
@Jakobud yeah, it's using IPFS which is similar to torrents for sure, you basically have to seed your content (or have someone seed it for you) and IPFS grabs the content from the peers.

Read more here: https://ipfs.io/
